"""
Plot dataframes for visual analysis
"""

import matplotlib.pyplot as plt

def plot_sensor_3d(df, axes_keys, title, axis_limits=None):
    """
    Plotting logic with optional axis limiting.
    axis_limits: tuple (min, max) e.g., (-2, 2)
    Generated by Gemini
    """
    label_cols = [
        'No loading', 'Driving(straight)', 'Driving(curve)',
        'Lifting(raising)', 'Lifting(lowering)',
        'Stationary processes', 'Turntable wrapping'
    ]

    labels = df[label_cols].idxmax(axis=1)
    unique_labels = labels.unique()

    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')

    for label in unique_labels:
        mask = labels == label
        ax.scatter(
            df.loc[mask, axes_keys[0]],
            df.loc[mask, axes_keys[1]],
            df.loc[mask, axes_keys[2]],
            label=label, s=10, alpha=0.6
        )

    # --- Limit Axes Here ---
    if axis_limits:
        ax.set_xlim(axis_limits)
        ax.set_ylim(axis_limits)
        ax.set_zlim(axis_limits)

    ax.set_xlabel(axes_keys[0])
    ax.set_ylabel(axes_keys[1])
    ax.set_zlabel(axes_keys[2])
    ax.set_title(title)
    ax.legend(loc='best', bbox_to_anchor=(1.1, 1))

    plt.show()


def plot_acceleration_3d(df):
    """
    Plots acceleration (x, y, z) in 3D space.
    Generated by Gemini
    """
    plot_sensor_3d(df, ['Acc.x', 'Acc.y', 'Acc.z'], "3D Acceleration by Process Class", (-0.5, 0.5))

def plot_gyroscope_3d(df):
    """
    Plots gyroscope (x, y, z) in 3D space.
    Generated by Gemini
    """
    plot_sensor_3d(df, ['Gyro.x', 'Gyro.y', 'Gyro.z'], "3D Gyroscope Rotation by Process Class", (-0.5, 0.5))

# Example usage:
# plot_acceleration_3d(your_dataframe)
# plot_gyroscope_3d(your_dataframe)